<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiskUsage.Core\DiskUsage.Core.csproj" />
    <ProjectReference Include="..\DiskUsage.Presentation\DiskUsage.Presentation.csproj" />
  </ItemGroup>

</Project>
