<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);xUnit1031</NoWarn>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dora.Widget.Abstractions\Dora.Widget.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Dora.Widget.Runtime\Dora.Widget.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Dora.Widget.SDK\Dora.Widget.SDK.csproj" />
    <ProjectReference Include="..\..\src\Dora.Widget.Host\Dora.Widget.Host.csproj" />
    <ProjectReference Include="..\..\samples\DiskUsage\DiskUsage.Core\DiskUsage.Core.csproj" />
    <ProjectReference Include="..\..\samples\DiskUsage\DiskUsage.Presentation\DiskUsage.Presentation.csproj" />
    <ProjectReference Include="..\..\samples\DiskUsage\DiskUsage.Widget\DiskUsage.Widget.csproj" />
  </ItemGroup>

</Project>
